// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB28wG3YmLP_idDfMWN0qqvFVH0vqVvyBg',
    appId: '1:478323279701:web:4679e3b8bc0db8ddc691dc',
    messagingSenderId: '478323279701',
    projectId: 'mediqtrack-d6aa7',
    authDomain: 'mediqtrack-d6aa7.firebaseapp.com',
    storageBucket: 'mediqtrack-d6aa7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFbJ3amN9Oqt90PBDXwRQAnq-aX8_5TiE',
    appId: '1:478323279701:android:834b5908f7de1f18c691dc',
    messagingSenderId: '478323279701',
    projectId: 'mediqtrack-d6aa7',
    storageBucket: 'mediqtrack-d6aa7.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB28wG3YmLP_idDfMWN0qqvFVH0vqVvyBg',
    appId: '1:478323279701:web:1e3765a854b5a689c691dc',
    messagingSenderId: '478323279701',
    projectId: 'mediqtrack-d6aa7',
    authDomain: 'mediqtrack-d6aa7.firebaseapp.com',
    storageBucket: 'mediqtrack-d6aa7.firebasestorage.app',
  );
}
